# Generated by Django 2.0.4 on 2018-06-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='dv',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dv',
        ),
        migrations.AddField(
            model_name='payroll',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Coach'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
    ]
